### ISSUE TITLE
[Bug]: Transfer command doesn't take amount as argument

### ISSUE THREAD

**Issue by Sonichigo** [Alphasians/Aina-Reglia#39]
### Detailed Description

I found this error in this project where ...

### Expected Behavior

I expected that...

### Current Behavior

Instead of [what should happen](#expected-behavior), I find...

### How can someone reproduce the behavior?

1. Goto...
2. Do...
3. Now...
4. Finally...

### What was you environment (os, browser, runtime, etc)?

Ubuntu Latest, Chrome Latest, Node14...

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sonichigo** [comment]
@krshdev Want to take this up?

**Comment by krshdev** [comment]
Yes, sure!
