### ISSUE TITLE
[Feat]: Help command `wallet` description should be more accurate

### ISSUE THREAD

**Issue by GaryStriving** [Alphasians/Aina-Reglia#44]
### Detailed Description

The current description of the `wallet` command is `Deposit money to bank`. However, what the command does is to show how much money you have.

I think that the description should be changed in order to make it match the command functionality.

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kkhitesh** [comment]
Can I work on this?

**Comment by Sonichigo** [comment]
Sure go ahead!! : )
