### ISSUE TITLE
[Bug]: `TypeError: Cannot read property 'ban' of null` error while using `aina@ban`

### ISSUE THREAD

**Issue by GaryStriving** [Alphasians/Aina-Reglia#45]
### Detailed Description

I found this error in this project while I was testing the bot in a private Discord server and I sent the message `aina@ban Lilliput` (which is the name of a bot in the server, but without the numbers of the tag).

### Expected Behavior

I expected Aina to return a pretty error message saying that the user does not exist.

### Current Behavior

Instead of [what should happen](#expected-behavior), I found that Aina sent the following message:
```
@Gary Strivin', An error occurred while running the command: TypeError: Cannot read property 'ban' of null
You shouldn't ever receive an error like this.
Please contact Sonichigo#1765.
```
Where I'm told that the error message should never appear and asks that I should contact Sonichigo.

### How can someone reproduce the behavior?

1. Create a server (or use a server where you have ban permissions).
2. Add AinaBot.
3. Send `aina@ban` with a name with a user that does not exist in the server.
4. Read the message returned.

### What was you environment (os, browser, runtime, etc)?

Using Aina's main instance

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sonichigo** [comment]
Hey @GaryStriving ! Ban command is a moderation command to be used in extreme case on the people of the server. If the user is not in the server then ban command won't work!

I could have misinterpreted the issue feel free to correct me!
