### ISSUE TITLE
[Feature]: Standardize the use of semicolons

### ISSUE THREAD

**Issue by GaryStriving** [Alphasians/Aina-Reglia#46]
### Detailed Description

While it is true that you don't need to use semicolon at the end of a statement in JavaScript (the newline is enough), code is much easier to understand when the style is consistent. However, there are files where semicolons are not used at all and others where they are.

An example of this is the pair of `transfer.js` and `unban.js`. In `transfer.js`, semicolons are used, but in `unban.js`.

Example snippet of `transfer.js`:
```js
async run (message, args) {
   const member = args.recipient;
   const user = await mongoCurrency.findUser(message.member.id, message.guild.id);
   const recipient = await mongoCurrency.findUser(member.id, message.guild.id);
   const amt = args.amount;

   if (user.coinsInWallet >= amt){
      await mongoCurrency.giveCoins(member.id, message.guild.id, amt );
      await mongoCurrency.deductCoins(message.member.id, message.guild.id, amt);
      message.reply(`You have transfered ${amt} Coins to <@!${member.id}>`); 
   }
   else {
     message.reply(`You don't have enough funds to transfer`);
   }
  }
```

Example snippet of `unban.js`:
```js
run (message, { userTounBan, reason }) {
    message.guild.fetchBans()
      .then(bans => {
        const user = bans.find(banInfo => banInfo.user.id === userTounBan)
        if (!user) {
          return message.reply('The mentioned ID is not banned')
        }
        message.guild
          .members.unban(userTounBan, reason)
          .then(() => {
            const unbanEmbed = new MessageEmbed()
              .addField('UnBanned:', userTounBan)
              .addField('Reason', reason)
              .setColor('#420626')
            message.channel.send(unbanEmbed)
          })
          .catch((e) => {
            message.say(
              'Something went wrong when trying to ban this user, I probably do not have the permission to ban him'
            )
            return console.error(e)
          })
      })
  }
```

### Contributing

- [X] I have read the project's contribution guidelines.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Anything else?

- It seems to me that the best option would be to always use semicolons. This is because it clarifies where each statement finishes, which makes it easier to read files with multiline statements.
- On our way, I do think that it would be a good idea to enforce a style guide to the project.

**Comment by Mansi-Binjola** [comment]
Hey @Sonichigo , before you assign me this task, I just to know if I got this right. My task will to change the syntax of the `unban.js` to `transfer.js` type syntax, right?

**Comment by Sonichigo** [comment]
Yes! You have to just remove  ; in transfer.js and save the file.

**Comment by Mansi-Binjola** [comment]
Hi there! While browsing the folders, I founded some js files which have ; being used.  The files are `coin.js`, `wallet.js` and `leaderboard.js`.  Shall I make changes in these files as well?

**Comment by Sonichigo** [comment]
Yeah, sure! Thanks for taking those up as well!
